#!/bin/bash

# Warn if server goes down unexpectedly
# 00,10,20,30,40,50 * * * * /Drugs/Cron/Other/check_is_metadata_up.sh
# Modified: Fri 24 Feb 2017 09:20:51 (Bob Heckel)

# Comma-separated list
NOTIFY=bob.heckel@taeb.com
PGM='/sas/config/Lev1/sas.servers status'
FLAG=/tmp/sas-01_is_down_flag.txt
UPTIME=$(uptime)

# Alert has already been emailed
if [ -e $FLAG ]; then 
  exit
fi

# SAS servers status:                          
# SAS Web Infrastructure Data Server is NOT up 
# SAS Metadata Server 1 is NOT up              
# SAS Object Spawner 1 is NOT up               
# SAS DIP Job Runner 1 is NOT up               
# SAS JMS Broker is NOT up                     
# SAS Cache Locator Service ins_41415 is NOT up
# SAS Web Server is NOT up                     
# SAS Web App Server SASServer1_1 is NOT up    
# SAS Environment Manager is NOT up            
# SAS Environment Manager Agent is NOT up      
#
# This will not:
# SAS servers status:                      
# SAS Web Infrastructure Data Server is UP 
# SAS Metadata Server 1 is UP              
# SAS Object Spawner 1 is UP               
# SAS DIP Job Runner 1 is UP               
# SAS JMS Broker is UP                     
# SAS Cache Locator Service ins_41415 is UP
# SAS Web Server is UP                     
# SAS Web App Server SASServer1_1 is UP    
# SAS Environment Manager is UP            
# SAS Environment Manager Agent is UP      
###if test `$PGM | grep -c "is UP"` -eq 1; then
if test `$PGM | grep -c "is NOT"` -eq 10; then
  echo 'uhoh'
  mail -s "Warning - SAS metadata server on sas-01 is down" $NOTIFY <<EOF
$UPTIME

sudo su - sas
/sas/config/Lev1/sas.servers start
/sas/sashome/SASDeploymentAgent/9.4/agent.sh start

Manually delete the checkflag /tmp/sas-01_is_down_flag.txt when the server is up

(This message was generated by $0)

EOF

  # Avoid sending the same email every x minutes when run via cron
  echo 'delete this flag when server is up' > $FLAG
fi
