#!/bin/bash

#  Purpose: Quickly checkin common code locations
#  Created: 20-Aug-2020 (Bob Heckel)
# Modified: 27-Mar-2022 (Bob Heckel)

for d in dotfiles code; do
  cd $HOME/$d && git status
  echo "ok to gitup $d dir (Y/n)? " && read yn &&
  if [ "$yn" != 'n' ];then
    # In a paranoid spirit, keep hostname semi-private but distinguish same-OS machines
    git add . && git commit -m "mod gitall $MACHTYPE-${HOSTNAME:0:4}"; git pull origin master && git push origin master
  else
    echo cancelled
  fi
  echo
done

for d in dotfiles code; do
  if [ "$yn" != 'n' ];then
    echo "Checking for ${d} fatals................"
    cd $HOME/${d} && \
    # Check for fatals "master pushes to master (local out of date)"
    #git remote show origin | grep --color=always 'local out of date' && \
    if [ `git remote show origin | grep -c 'local out of date'` -ge 1 ]; then
      echo "${fg_redbold}[FAIL]"${normal}
      echo "hint: cd ~/${d} && git merge && git push; git remote show origin"
    else
      echo '[OK]'
    fi
    cd -
  fi
done

echo ...done
