#!/bin/bash

#  Created: 20-Aug-2020 (Bob Heckel)
# Modified: 17-Dec-2021 (Bob Heckel)

for d in dotfiles code; do
  cd $HOME/$d && git status
  echo "ok to gitup $d dir (Y/n)? " && read yn &&
  if [ "$yn" != 'n' ];then
    # In a paranoid spirit, keep hostname semi-private but distinguish same-OS machines
    git add . && git commit -m "mod gitall $MACHTYPE-${HOSTNAME:0:4}"; git pull origin master && git push origin master
  else
    echo cancelled
  fi
  echo
done

for d in dotfiles code; do
  if [ "$yn" != 'n' ];then
    echo Checking for fatals...
    cd $HOME/$d && \
    # Check for fatals "master pushes to master (local out of date)"
    git remote show origin | grep --color=always 'local out of date' && \
    cd -
  fi
done

#echo ...done, do gfatal if needed
echo '...done, if needed do cd ~/dotfiles && git merge && git push; cd ~/code && git merge && git push; git remote show origin'
