From bheckel Thu Jun  7 08:11:39 2001
Return-Path: <jochen.schneider@mediaways.net>
Received: from mail.mediaways.net ([193.189.224.113])
	by walker.mail.mindspring.net (Earthlink Mail Service) with SMTP id tht84d.719l.37kbi73
	for <bheckel@mindspring.com>; Wed, 6 Jun 2001 17:28:45 -0400 (EDT)
Received: (qmail 12836 invoked by uid 4221); 6 Jun 2001 21:28:42 -0000
Received: from gmws-verl-de01.mediaways.net (HELO gmws-verl-de01) (195.71.226.118)
  by smtp-relay.mediaways.net with SMTP; 6 Jun 2001 21:28:42 -0000
Received: from ike.mediaways.net ([195.71.100.196]) by gmws-verl-de01.mediaways.net; Wed, 06 Jun 2001 23:28:06 +0000 (MET)
Message-ID: <3B1EA07A.5C3D54D9@mediaways.net>
Date: Wed, 06 Jun 2001 23:28:26 +0200
From: Jochen Schneider <jochen.schneider@mediaways.net>
Organization: mediaWays GmbH - A Telefonica Company
X-Mailer: Mozilla 4.77 [en] (Windows NT 5.0; U)
X-Accept-Language: en
MIME-Version: 1.0
To: bheckel@mindspring.com
Subject: Cygwin POP3 problems
References: <Springmail.105.991591926.0.41932900@www.springmail.com>
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Status: RO
X-Status: AF
Content-Length: 1831
Lines: 70

bheckel@mindspring.com wrote:
> 
> You are not alone :-)  I just noticed it yesterday after upgrading my whole system to the latest Cygwin setup.  The POP3 problem is the only case where I lost functionality.  The rest of the Cygwin improvements are pretty nice.  Thanks for checking.
> 
> Bob
> 
> Jochen Schneider <jochen.schneider@mediaways.net> wrote:
> thank god i'm not the only one! ;-)
> I can't remember exactly what i did, but I'll check that next Tuesday
> and will let You know.
> 
> Bye,
>  Jochen

Hi Bob,
well I was a bit busy this week, but my POP3.pm begins like this:

package Net::POP3;

Bye,
 Jochen

-- 
 jochen.schneider@mediaways.net    +49 5246 801404
   http://www.legasthenie-ist-keine-schande.de
<< Premature optimization is the root of all evil >>
