#!/bin/bash
####################################################################################
#  SAVED AS:      /Drugs/Cron/Daily/tmmEnrollmentTracking/tmmenrolltracking_v04_consolidation.sh
#                                                                         
#  CODED ON:      17-May-18 bheckel
#                                                                         
#  DESCRIPTION:   Execute jobs in series, email on success or failure.
#                                                                           
#  PARAMETERS:    Email addresses, SAS job(s)
#
#  LAST REVISED:  17-May-18 (bheckel) initial
####################################################################################

# EDIT
# NOTIFY=bob.heckel@monicell.com
NOTIFY=AnalyticsAteb@monicell.com

SAS=/sas/sashome/SASFoundation/9.4/sas
MSG="(this automated message was generated by $0)"

run_jobs(){
  echo DEBUG: running "$f"

  BASENM="${f%.*}"

  $SAS -sysin "$f" -log "${BASENM}.log"

  if [ $? -gt 1 ]; then
    echo DEBUG: "${f} failed"
    mail -s "Cron job ${f} has errors" $NOTIFY <<HERE1
SAS job $f running on $HOSTNAME has errors.

Please see the related log file: ${BASENM}.log





$MSG
HERE1
    echo 'DEBUG: Aborting remaining jobs, if any, due to failure'
    break
  else
    echo DEBUG: "${f} completed successfully"
    # mail -s "SAS job (${f}) completed successfully" $NOTIFY <<HERE2
# SAS job $f running on $HOSTNAME completed successfully.
#
#
#
#
#
# $MSG
# HERE2
  fi

}


# EDIT
# Group 1 must succeed
for f in \
         /sasdata/Cron/Daily/tmmEnrollmentTracking/tmmenrolltracking_v04_consolidation.sas \
         ; do
  run_jobs
done

# EDIT
# Try Group 2 if Group 1 is successful
# for f in \
#          /sasdata/Cron/Daily/tmmEnrollmentTracking/t.sas \
#          ; do
#   run_jobs
# done



         # /sasdata/Cron/Daily/tmmEnrollmentTracking/t.sas \
         # /sasdata/Cron/Daily/tmmEnrollmentTracking/tmmenrolltracking_v04_consolidation.sas \
