#!/bin/bash
##############################################################################
#     Name: encrypt
#
#  Summary: Weak encryption/decryption of text file.
#
#           This might be better:
#           To encrypt simply pipe the STDOUT of
#           the file to "crypt" and redirect it to
#           a new file name.
#
#           $ cat foo | crypt > foo.e
#           Enter key:
#
#           To unencrypt simply pipe the STDOUT of
#           the encrypted file to "crpyt" and
#           redirect it to a new file name.
#
#           $ cat foo.e | crypt > foo.new
#           Enter key:
#
#
# Adapted: Mon 17 Sep 2001 09:32:29 (Bob Heckel -- loosely adapted 
#                          http://www.linuxdoc.org/LDP/abs/html/extmisc.html)
##############################################################################

if [ $# = 1 ]; then
  echo 'Usage: $0 [-e|-d] filename'
  exit 1
fi

while getopts e:E:d:D: the_option
do
  case "$the_option" in
              # "Encode".  Might as well switch bytes (swab), too, for a
              # little extra obscurity.
     e | E )  cat $OPTARG | dd conv=swab,ebcdic >| "$OPTARG.encrypt.tmp"
              mv -v $OPTARG.encrypt.tmp $OPTARG;;
     d | D )  cat $OPTARG | dd conv=swab,ascii >| "$OPTARG.decrypt.tmp"
              mv -v $OPTARG.decrypt.tmp $OPTARG;;
        \? )  echo >&2 \       # unknown flag, can also use  * )
              "Usage: $0 [-e|-d] filename"
              exit 1;;
  esac
done

# Move argument pointer to next.
shift `expr $OPTIND - 1`      # same as shift $(($OPTIND - 1))
