
clipboardx() {       # <---Note: No PARAMS PASSED!
  # $1 refers to 1st param passed into this fn
  echo "first parm is $1 and second is $2"
}

# $1 refers to param passed by user
clipboardx foo $1



#!/bin/bash

function checker() {
echo 1 $1
echo 2 $2
echo 3 $3

  R1=$(find $1 -name '*.xlsx' -mtime 0 2>/dev/null)

  if [ -z "$R1" ] ; then
    echo $1 is missing
    mail -s "Warning - report(s) stale or missing" $1 <<EOF
${3}

(This message was generated by $0)

EOF

  else
    echo $1 is not stale or missing
  fi
}

# Comma-separated list
NOTIFY=bob.heckel@omnicell.com
UPTIME=$(uptime)
# R1PTH=/sasdata/Personnel/bob/report_checker/
R1PTH=/sasreports/Reporting/TMM/Daily/autoChain

checker "$R1PTH" "$NOTIFY" "$UPTIME"
