#!/bin/bash

for d in dotfiles code; do
  cd ~/$d && 
  echo "ok to gitup $d dir?" && read &&
  git status
  git add .
  git commit -m "mod gitall"
  git pull origin master && git push origin master
done
