#!/bin/bash

cd ~/dotfiles && 
echo "ok to gitup?" && read && git status && git add . && git commit -m "mod" && git pull origin master && git push origin master
cd ~/code &&
echo "ok to gitup?" && read && git status && git add . && git commit -m "mod" && git pull origin master && git push origin master
