#!/bin/sh
##############################################################################
#     Name: howdo.sh
#
#  Summary: Run after the 8 IOCODE queries have run to determine how you did
#           and to create a total matched file.
#
#  Created: Fri 13 Sep 2002 16:18:58 (Bob Heckel)
# Modified: Wed 17 Sep 2003 14:48:22 (Bob Heckel)
##############################################################################
  
Usage() {
  echo "
Usage: `basename $0` INPUTFILE
  E.g. `basename $0` junk.txt

  Calculates success percentage, combines match files."
}

N_EXPECTED_ARGS=1
# Created on each run.
FINAL="$TMP/match.ALL.out"
# Generated by IOCODE.
FILES=($TMP/match.direct.out \
       $TMP/match.minor.out \
       $TMP/match.exception.out \
       $TMP/match.reverse.out \
       $TMP/match.slash.out \
       $TMP/match.occunrest.out \
       $TMP/match.occrestrict.out \
       $TMP/match.fuzz.out)

if [ $# -ne $N_EXPECTED_ARGS ]; then 
  Usage
  exit 2
fi

if [ ! -e "$1" ]; then
  Usage
  exit 3
fi

for f in ${FILES[*]}; do
  if [ -e "$f" ]; then
    AVAILABLE="$AVAILABLE $f"
  fi
done

if ! test "$AVAILABLE"; then
  # Empty string, no files exist
  Usage
  exit 4
fi

###DOROTHY=`wc -l BEN2PT1.clean.txt | awk '{print $1}'`
###DOROTHY=`wc -l smallBENtest.txt | awk '{print $1}'`
DOROTHY=`wc -l "$1" | awk '{print $1}'`
echo "Input file ($1) lines: $DOROTHY"

echo "Intermediate processing AVAILABLE were $AVAILABLE"

SUMLINES=`wc -l $AVAILABLE | grep 'total' | awk '{print $1}'`
echo "Total lines reviewed were $SUMLINES"
TOT=`echo "$SUMLINES / $DOROTHY * 100" | bc -lwq`
printf "%.2f%% matched\n" $TOT 

cat $AVAILABLE >| $FINAL

echo "Total lines matched: "
wc -l $FINAL

exit 0
