Select lk.SID,
       se.CLIENT_IDENTIFIER,
       se.username,
       se.OSUser,
       se.Machine,
       DECODE(lk.TYPE,
              'TX',
              'Transaction',
              'TM',
              'DML',
              'UL',
              'PL/SQL User Lock',
              lk.TYPE) lock_type,
       DECODE(lk.lmode,
              0,
              'None',
              1,
              'Null',
              2,
              'Row-S (SS)',
              3,
              'Row-X (SX)',
              4,
              'Share',
              5,
              'S/Row-X (SSX)',
              6,
              'Exclusive',
              TO_CHAR(lk.lmode)) mode_held,
       DECODE(lk.request,
              0,
              'None',
              1,
              'Null',
              2,
              'Row-S (SS)',
              3,
              'Row-X (SX)',
              4,
              'Share',
              5,
              'S/Row-X (SSX)',
              6,
              'Exclusive',
              TO_CHAR(lk.request)) mode_requested,
       TO_CHAR(lk.id1) lock_id1,
       TO_CHAR(lk.id2) lock_id2,
       ob.owner,
       ob.object_type,
       ob.object_name,
       lk.Block,
       se.lockwait
  FROM v$lock lk, dba_objects ob, v$session se
 WHERE lk.SID = se.SID
   and se.SCHEMANAME like 'SE%'
   AND lk.id1 = ob.object_id(+)
and block = 1;
