From bheckel Mon Jul 16 09:18:52 2001
Return-Path: <cclayton@maximgroup.com>
Received: from spf3.us4.outblaze.com ([205.158.62.25])
	by bissell.mail.mindspring.net (Earthlink Mail Service) with ESMTP id tl5q6c.ovt.37kbi66
	for <bheckel@mindspring.com>; Mon, 16 Jul 2001 09:14:52 -0400 (EDT)
Received: from e220-15.allegisgroup.com (mail.allegisgroup.com [216.152.109.5])
	by spf3.us4.outblaze.com (8.11.0/8.11.0) with ESMTP id f6GDEp121331
	for <rsh@technologist.com>; Mon, 16 Jul 2001 13:14:51 GMT
Received: from e220-5.allegisgroup.com ([10.10.50.150])
          by e220-15.allegisgroup.com
          (InterMail vK.4.03.02.00 201-232-124 license 4788eef65eb95011980670a2cb753138)
          with ESMTP
          id <20010716131641.ETWL5400.e220-15@e220-5.allegisgroup.com>
          for <rsh@technologist.com>; Mon, 16 Jul 2001 09:16:41 -0400
Received: from maximgroup.com (localhost [127.0.0.1])
	by e220-5.allegisgroup.com (8.8.8+Sun/8.8.8) with ESMTP id JAA12855
	for <rsh@technologist.com>; Mon, 16 Jul 2001 09:16:40 -0400 (EDT)
Message-ID: <3B52E9C6.378EFFB0@maximgroup.com>
Date: Mon, 16 Jul 2001 09:19:02 -0400
From: Courtney Clayton <cclayton@maximgroup.com>
Reply-To: cclayton@maximgroup.com
Organization: Maxim Group, Inc.
X-Sender: "Courtney Clayton" <cclayton@ismtp.allegisgroup.com>
X-Mailer: Mozilla 4.7 [en]C-CCK-MCD AllegisGroup  (WinNT; U)
X-Accept-Language: en
MIME-Version: 1.0
To: rsh@technologist.com
Subject: Re: tech quiz
References: <3B4E18E5.791F055D@maximgroup.com> <20010714112507.A872@PARSIFAL>
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Status: RO
X-Status: F
Content-Length: 1422
Lines: 42

Bob,

I received the results of your quiz.  You did well above average.  I'm looking
forward to lunch tomorrow.  See ya at Thunderbacks!!

Courtney Clayton

Bob Heckel wrote:

> Hi Courtney,
>
> Just finished the Perl quiz.  Sat 14 Jul 2001 11:24:08.
>
> Bob
>
> Courtney Clayton wrote at 20010712 18:09:
> > Bob,
> >
> > Thanks for taking time today to speak with me.  I really enjoyed getting
> > to know you and about the career opportunities in which you're
> > interested.  I'm looking forward to our lunch next Tuesday at 11:30 at
> > Thunderbacks!!  New restaraunts are always a plus on my end!!  I'm
> > attaching the directions to the quiz in Perl.  Good luck!  Talk to you
> > soon.
> >
> > Sincerely,
> >
> > Courtney Clayton
> >
> > To take the Qwiztek, log onto www.qwiztek.com. Click on the IT test
> > link. Then click on the Test Area link on the left side of the screen.
> > Enter your first name, last name and Access Code, and then click Submit
> > Login. Your Access Code is included is included in the email.   Several
> > Candidate Information Questions appear on the screen. Enter requested
> > information; then click Submit. Detailed instructions are provided for
> > this test. After reading, click Begin Evaluation. When you finish,
> > please email me and I will receive the results.
> > Thanks and good luck.
> >
> >
> > Access Code: 3352-POKT-5209


