#!/bin/bash

cd ~/onedrive &&
find . -type d | grep -i "${1}"
for f in $(find . | grep orion- | grep -P '.*pck|.*sql|.*prc|.*fnc'); do grep -i --with-filename "${1}" $f; done >| ~/tmp/prj.out 
vim -c "/${1}" ~/tmp/prj.out
