#!/bin/bash
####################################################################################
#  SAVED AS:       DEBUG!!!!!!!!!!!!!!!!!!         run_jobs_email_status.sh
#                                                                         
#  CODED ON:                21APR2015 by Bob Heckel
#                                                                         
#  DESCRIPTION:             Execute jobs in series, email on success or failure.
#                                                                           
#  PARAMETERS:              Email addresses, SAS jobs
#
#  LAST REVISED:                                                          
#   ddmonyyyy (initials) (description of change)                          
#
####################################################################################

NOTIFY=bob.heckel@a.com
SAS=/usr/local/SAS94/sashome/SASFoundation/9.4/sas
MSG="(this automated message was generated by $0)"

run_jobs(){
  echo DEBUG: running "$f"

  BASENM="${f%.*}"

  $SAS -sysin "$f" -log "${BASENM}.log"

  if [ $? -gt 1 ]; then
    echo DEBUG: fail!!!
    XXXmail -s "SAS job (${f}) has errors" $NOTIFY <<HERE1
SAS job $f running on talon3 has errors, please see the related log file.


$MSG
HERE1
    echo 'DEBUG: Aborting this series due to failure'
    break
  else
    echo DEBUG: success
    XXXmail -s "SAS job (${f}) completed successfully" $NOTIFY <<HERE2
SAS job $f running on talon3 completed successfully.


$MSG
HERE2
  fi

}


for f in \
         /Drugs/bheckel/run_cron/t3.sas \
         /Drugs/bheckel/run_cron/t4.sas \
         /Drugs/bheckel/run_cron/"t 4".sas \
         ; do
  run_jobs
done

for f in \
         /Drugs/bheckel/run_cron/t5.sas \
         /Drugs/bheckel/run_cron/t6.sas \
         ; do
  run_jobs
done
