#!/bin/bash
####################################################################################
#  SAVED AS:             run_jobs_email_status_abort.sh
#                                                                         
#  CODED ON:             02-Mar-16 (bheckel)
#                                                                         
#  DESCRIPTION:          Execute jobs in series, aborting on any failure, email on 
#                        success (optional) or failure
#                                                                           
#  PARAMETERS:           Email addresses, SAS jobs, EMAILONSUCCESS flag
#
#  LAST REVISED:                                                          
#   02-Mar-16 (bheckel)  Initial
####################################################################################

NOTIFY=bob.heckel@taeb.com
SAS=/sas/sashome/SASFoundation/9.4/sas
BODYMSG="(this automated message was generated by $0)"
EMAILONSUCCESS=0  # 1 is yes

run_jobs(){
  echo DEBUG: running "$f"

  BASENM="${f%.*}"

  $SAS -sysin "$f" -log "${BASENM}.log" -print "${BASENM}.lst"

  # 2+ indicate SAS ERROR:
  if [ $? -gt 1 ]; then
    echo DEBUG: fail!!!
    mail -s "[cron] ${f} has errors" $NOTIFY <<HERE1
SAS job $f running on $HOSTNAME has errors, please see the related log file ${BASENM}.log


$BODYMSG
HERE1
    echo 'DEBUG: Aborting this series due to failure'
    break
  else
    echo DEBUG: success
    if [ $EMAILONSUCCESS -eq 1 ]; then
    mail -s "[cron] ${f} completed successfully" $NOTIFY <<HERE2
SAS job $f running on $HOSTNAME completed successfully.


$BODYMSG
HERE2
    fi
  fi
}


# Group 1 - stop if any job fails but continue with Group 2 either way
for f in \
         /Drugs/Personnel/bob/Cron/t2.sas \
         /Drugs/Personnel/bob/Cron/t3.sas \
         /Drugs/Personnel/bob/Cron/t4.sas \
         ; do
  run_jobs
done

# Group 2 - stop if any job fails
for f in \
         /Drugs/Personnel/bob/Cron/t5.sas \
         /Drugs/Personnel/bob/Cron/t6.sas \
         ; do
  run_jobs
done
