#!/bin/bash
##############################################################################
#     Name: s9
#
#  Summary: Alpha.  Assumes sas.html exists.  For now use this to run:
#           s9 '%quote' && st ~/tmp/testing/junk.html
#
#  Created: Thu 22 Jul 2004 11:00:09 (Bob Heckel)
##############################################################################
  
Usage() {
  echo "Usage: `basename $0` searchword
  E.g. `basename $0` 'sysfunc' && st ~/tmp/testing/junk.html
  Searches sas.com for v9.1 keyword"
  exit 1
}

N_EXPECTED_ARGS=1

if [ "$#" -ne $N_EXPECTED_ARGS ]; then 
  Usage
fi

# TODO can't spawn moz
grep -i ".*>$1" $HOME/tmp/testing/sas.html | sed 's/<div.*>//' | sed 's/<.*blank.htm.*>//' | sed 's/<.*span.*>//' | sed 's#/onlinedoc#http://support.sas.com/onlinedoc#' >| $HOME/tmp/testing/junk.html
