#!/bin/sh
##############################################################################
#    Name: sod (s/b symlinked as ~/bin/sod)
#
# Summary: Size of directory.  Recursive sum of bytes in directory.
#          Using the ls -l "total" works the same but since it reports in
#          system dependent blocksize , ls is less precise than this program.
#
# Adapted: Mon, 03 Jan 2000 19:49:30 (Bob Heckel -- Effective Awk Programming)
# Modified: Thu 14 Dec 2006 14:47:24 (Bob Heckel)
##############################################################################

\ls -lR $1 | awk '{ s += $5 } END{ s=s/1000000; print "about " int(s) " MB"}'
