#!/bin/sh
##############################################################################
#     Name: tmpsave
#
#  Summary: Cheap backup of files that have had way too much editing done to 
#           them to risk a local hard drive failure.
#
#           TODO allow override daeb
#
# Created: Wed May 28 11:22:45 2003 (Bob Heckel)
# Modified: Fri 27 Feb 2004 10:35:18 (Bob Heckel)
##############################################################################

Usage() {
  echo "Usage: `basename $0` file_to_scp
  E.g. `basename $0` foo.txt
  Copies a local file to a daeb tmp dir for backup purposes."
  exit 1
}

N_EXPECTED_ARGS=1

if [ "$#" -ne $N_EXPECTED_ARGS ]; then
  Usage
fi

d=`date +%Y%m%d-%s`
scp "$1" bheckel@daeb:tmp/$1.$d
