'SEE split_matrix_depts.xls FOR POSSIBLE ENHANCEMENTS.
Option Explicit
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Program Name: copied.bas
'
' Summary: Assumes another open spdsht. has a selected region active.
'          Creates new workbook, switches to selected region spdsht., copies, 
'          switches back and pastes, saves oNewBk.
'   Usage: copied(name of new file based on selection of other spdsht,
'                 name of file with highlighted area)
'
' Created: Thu Jun 10 1999 11:02:04 (Bob Heckel)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Function Copied(sNewFileName as String, sFileWithHilite as String) as Boolean
  On Error GoTo ENTROPY
  Dim oNewBk As Excel.Workbook

  Set oNewBk = Workbooks.Add
    oNewBk.SaveAs FileName:= sNewFileName
    
    Workbooks(sFileWithHilite).Activate
    Selection.Copy
    Workbooks(sNewFileName).Activate
    ActiveSheet.Paste
    ActiveWorkbook.Save
    ActiveWorkbook.Close
  Set oNewBk = Nothing

  Copied = True

' Single exit point.
DAMAGEDEXIT:
  Exit Function

ENTROPY:
  If Err.Number <> 0 Then
    strMsg = "Error # " & Str(Err.Number) & " was generated by " _
              & Err.Source & Chr(13) & "Description: " & Err.Description
    MsgBox strMsg, , "An error has occurred in Function Copied. " _
           & erl, Err.Helpfile, Err.HelpContext
  End If
  Resume DAMAGEDEXIT
End Function
