Attribute VB_Name = "modCopied"
Option Explicit
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Program Name: copied.bas
'
' Summary: Assumes another open spdsht. has a selected region active.
'          Creates new workbook, switches to selected region spdsht., copies,
'          switches back and pastes, saves oNewBk.
'   Usage: Copied(name of new file based on selection of other spdsht,
'                 name of file with highlighted area)
'
' Created: Thu Jun 10 1999 11:02:04 (Bob Heckel)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Function Copied(sNewFileName As String, sFileWithHilite As String) As Boolean
  On Error GoTo ENTROPY
  Dim oNewBk As Excel.Workbook
  Dim sMsg As String
  Dim sFullQualNewFilename As String
  
  ' Toggle.
  '''Const SAVETOHERE = "D:\matrixsplit\inst\"
  Const SAVETOHERE = "D:\matrixsplit\eng\"

  Set oNewBk = Workbooks.Add
    sFullQualNewFilename = SAVETOHERE & sNewFileName
    oNewBk.SaveAs FileName:=sFullQualNewFilename
    
    Workbooks(sFileWithHilite).Activate
    Selection.Copy
    Workbooks(sNewFileName).Activate
    ActiveSheet.Paste
    ActiveWorkbook.Save
    ActiveWorkbook.Close
  Set oNewBk = Nothing

  Copied = True

' Single exit point.
DAMAGEDEXIT:
  Exit Function

ENTROPY:
  If Err.Number <> 0 Then
    sMsg = "Error # " & Str(Err.Number) & " was generated by " _
              & Err.Source & Chr(13) & "Description: " & Err.Description
    MsgBox sMsg, , "An error has occurred in Function Copied. " _
           & erl, Err.Helpfile, Err.HelpContext
  End If
  Resume DAMAGEDEXIT
End Function
