options mlogic mprint sgen source2;

%macro BuildPlots;
  %global OUTCGMS;

  /* Controlled build workaround */
  %if &SYSUSERID eq rsh86800 %then %do;
    %let DPSVR = \\Rtpdsntp032;
    %let DPDIRROOT = &DPSVR\DataPostArchive\Ventolin_HFA;
    %let PUCCSVR = \\rtpsawnv0312;
    %let PLOTDIRROOT = &PUCCSVR\pucc\plots\Ventolin_HFA;
  %end;
  %else %if &SYSUSERID eq mxb85875 %then %do;
    %let DPDIRROOT = P:;
    %let PLOTDIRROOT = L:;
  %end;

  libname INPUTDIR "&DPDIRROOT\OUTPUT_COMPILED_DATA\Analytical_byTest";
  libname INPUTDI2 "&DPDIRROOT\OUTPUT_COMPILED_DATA";

  %include "&PLOTDIRROOT\CODE\100_build_VHFA_plots.sas";

  %let OUTCGMS = &PLOTDIRROOT\OUTPUT\Formatted\cgm200;  /* PRS02088 */
  /* 2010-04-20 the ind specs are currently being ignored but remain in case of rollback of business requirements */
  /*%macro build(prodname,  dsn       ,  varname,           strength,duration,duration_string,dateSort,minMeanSpec,maxMeanSpec,minSpec,maxSpec,statlbl,stat);*/
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , all     , All      , Test , -99  , 210  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , all     , All      , Mfg  , -99  , 210  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , oneyear , One Year , Test , -99  , 210  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , oneyear , One Year , Mfg  , -99  , 210  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , all     , All      , Test , -99  , 2    , -99  , 2.5  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , all     , All      , Mfg  , -99  , 2    , -99  , 2.5  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , oneyear , One Year , Test , -99  , 2    , -99  , 2.5  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , oneyear , One Year , Mfg  , -99  , 2    , -99  , 2.5  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , all     , All      , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , all     , All      , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , oneyear , One Year , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , oneyear , One Year , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , all     , All      , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , all     , All      , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , oneyear , One Year , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , oneyear , One Year , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , all     , All      , Test , 28   , 55   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , all     , All      , Mfg  , 28   , 55   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , oneyear , One Year , Test , 28   , 55   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , oneyear , One Year , Mfg  , 28   , 55   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , all     , All      , Test , -99  , 15   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , all     , All      , Mfg  , -99  , 15   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , oneyear , One Year , Test , -99  , 15   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , oneyear , One Year , Mfg  , -99  , 15   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , all     , All      , Test , 25   , 42   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , all     , All      , Mfg  , 25   , 42   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , oneyear , One Year , Test , 25   , 42   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , oneyear , One Year , Mfg  , 25   , 42   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , all     , All      , Test , -99  , 7    , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , all     , All      , Mfg  , -99  , 7    , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , oneyear , One Year , Test , -99  , 7    , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , oneyear , One Year , Mfg  , -99  , 7    , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , all     , All      , Test , 22.7 , 27.7 , 21.4 , 29.0 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , all     , All      , Mfg  , 22.7 , 27.7 , 21.4 , 29.0 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , oneyear , One Year , Test , 22.7 , 27.7 , 21.4 , 29.0 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , oneyear , One Year , Mfg  , 22.7 , 27.7 , 21.4 , 29.0 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , all     , All      , Test , 1.29 , 1.49 , 1.21 , 1.57 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , all     , All      , Mfg  , 1.29 , 1.49 , 1.21 , 1.57 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , oneyear , One Year , Test , 1.29 , 1.49 , 1.21 , 1.57 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , oneyear , One Year , Mfg  , 1.29 , 1.49 , 1.21 , 1.57 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , all     , All      , Test , 16.9 , 18.3 , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , all     , All      , Mfg  , 16.9 , 18.3 , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , oneyear , One Year , Test , 16.9 , 18.3 , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , oneyear , One Year , Mfg  , 16.9 , 18.3 , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , all     , All      , Test , 67  , 83  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , oneyear , One Year , Test , 67  , 83  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 200 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);

  /* PRS02070 */
  /*%macro build(prodname,  dsn       ,  varname,           strength,duration,duration_string,dateSort,minMeanSpec,maxMeanSpec,minSpec,maxSpec,statlbl,stat);*/
  %let OUTCGMS = &PLOTDIRROOT\OUTPUT\Formatted\cgm60;
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , all     , All      , Test , -99  , -210 , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , all     , All      , Mfg  , -99  , -210 , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , oneyear , One Year , Test , -99  , -210 , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , oneyear , One Year , Mfg  , -99  , -210 , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , MOISTURE   , MOISTURE                , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE               , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , all     , All      , Mfg  , -99  , 2    , -99  , 2.5  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , oneyear , One Year , Test , -99  , 2    , -99  , 2.5  , Avg    , mean);
  %build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , oneyear , One Year , Mfg  , -99  , 2    , -99  , 2.5  , Avg    , mean);
  ***%build(Ventolin HFA , LEAK       , LEAK_RATE_PERCENT       , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , all     , All      , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , all     , All      , Test , -99  , -99  , 72   , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , all     , All      , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , oneyear , One Year , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , oneyear , One Year , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_BEG_DTU              , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , all     , All      , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , all     , All      , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , oneyear , One Year , Test , 76   , 104  , 72   , 108  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , oneyear , One Year , Mfg  , 76   , 104  , 72   , 108  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_END_DTU              , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , DTU        , AS_DIFF_DTU             , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , all     , All      , Test , 28   , 55   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , all     , All      , Mfg  , 28   , 55   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , oneyear , One Year , Test , 28   , 55   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , oneyear , One Year , Mfg  , 28   , 55   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_THROAT            , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , all     , All      , Test , -99  , 15   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , all     , All      , Mfg  , -99  , 15   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , oneyear , One Year , Test , -99  , 15   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , oneyear , One Year , Mfg  , -99  , 15   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM012            , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , all     , All      , Test , 28   , 42   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , all     , All      , Mfg  , 28   , 42   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , oneyear , One Year , Test , 28   , 42   , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , oneyear , One Year , Mfg  , 28   , 42   , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM345            , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , all     , All      , Test , -99  , 7    , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , all     , All      , Mfg  , -99  , 7    , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , oneyear , One Year , Test , -99  , 7    , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , oneyear , One Year , Mfg  , -99  , 7    , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_SUM67F            , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_ACTUATOR          , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , CI         , AS_CI_TOTAL_EXDEVICE    , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , all     , All      , Test , 10.2 , -99  , 9.6  , 13.0 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , all     , All      , Test , -99  , -99  , 9.6  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , all     , All      , Mfg  , 10.2 , 12.4 , 9.6  , 13.0 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , all     , All      , Mfg  , -99  , -99  , 9.6  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , oneyear , One Year , Test , 10.2 , 12.4 , 9.6  , 13.0 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , oneyear , One Year , Test , -99  , -99  , 9.6  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , oneyear , One Year , Mfg  , 10.2 , 12.4 , 9.6  , 13.0 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_TOTAL_MASS          , 60 , oneyear , One Year , Mfg  , -99  , -99  , 9.6  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , all     , All      , Test , 1.34 , 1.55 , 1.26 , 1.63 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , all     , All      , Mfg  , 1.34 , 1.55 , 1.26 , 1.63 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , oneyear , One Year , Test , 1.34 , 1.55 , 1.26 , 1.63 , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , oneyear , One Year , Mfg  , 1.34 , 1.55 , 1.26 , 1.63 , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_CONCENTRATION       , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONVALVE_WT      , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGINSUSPENSION_WT , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , TDC_DRUGONCANWALL_WT    , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , all     , All      , Test , 6.9  , 8.3  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , all     , All      , Mfg  , 6.9  , 8.3  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , oneyear , One Year , Test , 6.9  , 8.3  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , oneyear , One Year , Mfg  , 6.9  , 8.3  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , TDC        , CONTENT_WEIGHT          , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , all     , All      , Test , 67  , 83  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , all     , All      , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , all     , All      , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , oneyear , One Year , Test , 67  , 83  , -99  , -99  , Avg    , mean);
  %build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , oneyear , One Year , Test , -99  , -99  , -99  , -99  , StdDev , std);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , Avg    , mean);
  ***%build(Ventolin HFA , SHOTWEIGHT , SHOT_WEIGHT             , 60 , oneyear , One Year , Mfg  , -99  , -99  , -99  , -99  , StdDev , std);
%mend BuildPlots;
%BuildPlots;
