
/********************************************************************************
 *  Generated by XML Mapper, 902000.3.6.20090116170000_v920
 ********************************************************************************/

/*
 *  Environment
 */
filename  acc 'U:\code\sas\acc.xml';
filename  SXLEMAP 'acc.map';
libname   acc xml xmlmap=SXLEMAP access=READONLY;

/*
 *  Catalog
 */

proc datasets lib=acc; run;

/*
 *  Contents
 */

proc contents data=acc.participant varnum; run;

/*
 *  Printing
 */

title 'Table participant';
proc print data=acc.participant; run;
title;


/*
 *  Local Extraction
 */

DATA participant; SET acc.participant; run;

