
init:                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
hostcl = loadclass('SASHELP.fsp.hauto');                                                                                                                                                                                                                        
declare char (1000) ver errdesc;                                                                                                                                                                                                                                
declare object dobj dobje ;                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                
call send(hostcl, '_NEW_', dobj, 0, 'DataLink.AspenTech.Batch21.Adapter.WebService');                                                                                                                                                                           
call send(dobj, '_SET_PROPERTY_', 'WebServiceURL', 'http://zebsamoc002/Batch21ws/Aspentech.Batch21.Web.Services.dll?Handler=Default');                                                                                                                          
call send(dobj, '_SET_PROPERTY_', 'WebserviceQueryXML', '<Datasource xmlns="Aspentech.Batch21" name="zeb01"><Area name="SDMAN"><BatchQuery xmlns="Aspentech.Batch21" dataSourceName="" areaName=""><TimeRange start="2009-02-01T17:59:59" end="2009-03-31T18:00:
01" /> </BatchQuery></Area></Datasource>');                                                                                                                                                                                                                     
call send(dobj, '_SET_PROPERTY_', 'XMLHeader', '<?xml version="1.0"?>');                                                                                                                                                                                        
call send(dobj, '_SET_PROPERTY_', 'Timeout', '60000');                                                                                                                                                                                                          
***call send(dobj, '_DO_', 'ExecuteForXMLFile','us1_auth', 'uzy74946', '7PanthersUZY', "C:\cygwin\home\bheckel\projects\datapost\tmp\batch21\batch21\DLI.xml", 1);                                                                                              
call send(dobj, '_DO_', 'ExecuteForXMLFile', "C:\cygwin\home\bheckel\projects\datapost\tmp\batch21\batch21\DLI.xml", 1, 0, 'us1_auth', 'uzy74946', '7PanthersUZY');                                                                                             
call send(dobj, '_GET_PROPERTY_', 'Version', ver);                                                                                                                                                                                                              
/* If Obj_B21WS.ErrorStatus.EventID = 0 Then ... */                                                                                                                                                                                                             
call send(dobj, '_GET_PROPERTY_', 'ErrorStatus', dobje);                                                                                                                                                                                                        
call send(dobje, '_GET_PROPERTY_', 'EventID', errnum);                                                                                                                                                                                                          
call send(dobje, '_GET_PROPERTY_', 'Description', errdesc);                                                                                                                                                                                                     
call send(dobj, '_TERM_');                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                
if errnum eq 0 then do;                                                                                                                                                                                                                                         
  put "XML saved to file &xmlfile";                                                                                                                                                                                                                             
  put 'DLI' ver= errnum= errdesc=;                                                                                                                                                                                                                              
end;                                                                                                                                                                                                                                                            
else do;                                                                                                                                                                                                                                                        
  put 'ERROR in XML read/write';                                                                                                                                                                                                                                
  put errnum= errdesc=;                                                                                                                                                                                                                                         
end;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
return;
