 /* MLOGIC will help you determine instructional code which will be what
  * executes on the local side. MLOGIC specifies whether the macro processor
  * prints a message whenever the SAS System executes any macro instructional
  * code within a macro.  Any statements produced by MLOGIC will happen on the
  * local side and everything else will be executed on the remote host.
  *
  * MPRINT will help you determine text which will be what executes on the
  * remote side.  MPRINT displays SAS statements generated by macro execution.
  * Any statements produced by MPRINT that appear between the
  * RSUBMIT/ENDRSUBMIT block will happen on the remote host and everything
  * else will be executed on the local host.  
  */
options mlogic mprint sgen NOsource;


 /* Run from PC via ;z */

%include 'c:/cygwin/home/bqh0/code/sas/connect_setup.sas';
signon cdcjes2;

%macro Test; 
  rsubmit;                                       /* text */
  %let dsn=L;                                    /* compiled code */
   %if %quote(&sysscpl) eq %str(OS) %then        /* compiled code */
     %do;
      libname L 'BQH0.SASLIB';                   /* text  */
      proc print data=&dsn..SHOEY(obs=5); run;   /* text */
   %end;                                         /* compiled code */
  endrsubmit;                                    /* text */
%mend Test;                                     
%Test  

signoff cdcjes2;
