
libname l '.';
libname GDM oracle user=dgm_dist_r password=lsice45read path=kuprd613 schema=dgm_dist;

proc sql;
 create table l.ods as 
   SELECT
     VW_ZEB_MERPS_PRCS_ORD_HEADER.PRCS_ORD_NUM format=$12.,
     VW_ZEB_MERPS_PRCS_ORD_HEADER.ACTUAL_START_DT format=DATETIME20.,
     VW_ZEB_MERPS_PRCS_ORD_HEADER.QUANTITY_DELIVERED format=15.3,
     VW_ZEB_MERPS_PRCS_ORD_HEADER.UOM_FOR_QUANTITY_VAL format=$9. AS UOM_FOR_QUANTITY_VAL_PARENT,
     VW_ZEB_MERPS_PRCS_ORD_HEADER.ALTERNATE_BOM format=$2.,
     VW_ZEB_MERPS_MATERIAL_INFO1.MAT_DESC format=$120.,
     VW_ZEB_MERPS_PRCS_ORD_MATERIAL.BAT_NUM format=$10. AS BAT_NUM
   FROM GDM.VW_ZEB_MERPS_PRCS_ORD_HEADER AS VW_ZEB_MERPS_PRCS_ORD_HEADER 
   WHERE VW_ZEB_MERPS_PRCS_ORD_HEADER.ACTUAL_START_DT gt '01MAR09:00:00:00'dt and VW_ZEB_MERPS_PRCS_ORD_HEADER.ACTUAL_START_DT lt '31MAR09:00:00:00'dt
   ORDER BY VW_ZEB_MERPS_PRCS_ORD_HEADER.ACTUAL_FINISH_DT DESCENDING, VW_ZEB_MERPS_PRCS_ORD_HEADER.PRCS_ORD_NUM, VW_ZEB_MERPS_PRCS_ORD_MATERIAL.RESERVATION_ITEM
   ;
quit;
