#!/bin/bash

#  Created: 08-Oct-2018 (Bob Heckel)
# Modified: 28-Aug-2020 (Bob Heckel)
#
# Simplified version of sasrun
#
# vim mapping:
# au BufNewFile,BufRead,BufEnter *.sas nmap ;z :!~/code/sas/sasrun2 "%:p"<CR>

tmpCODE="c:/temp/tmpsas.$$.sas"
tmpLOG="c:/temp/tmpsas.$$.log"
tmpLST="c:/temp/tmpsas.$$.lst"

#SAS94WIN='C:/Progra~1/SASHome/SASFoundation/9.4/sas.exe -config C:\Progra~1\SASHome\SASFoundation\9.4\nls\u8\sasv9.cfg'
#TODO
SAS94WIN='C:/Progra~1/SASHome/SASFoundation/9.4/sas.exe -CONFIG "C:\Users\boheck\OneDrive - SAS\misc\atlas_sas94_boheck.cfg"'

cat "$1" >| $tmpCODE

#$SAS94WIN -sysin $tmpCODE -log $tmpLOG -print $tmpLST
C:/Progra~1/SASHome/SASFoundation/9.4/sas.exe -CONFIG "C:\Users\boheck\OneDrive - SAS\misc\atlas_sas94_boheck.cfg" -sysin $tmpCODE -log $tmpLOG -print $tmpLST

if [ -e $tmpLST ];then
  $EDITOR -R -n -o -c '/^ERROR.*:/' $tmpLOG $tmpLST
  mv -f $tmpLOG c:/temp/tmpsas.lastrun.sasrun.log
  mv -f $tmpLST c:/temp/tmpsas.lastrun.sasrun.lst
else
  $EDITOR -R -n -o -c '/^ERROR.*:/' $tmpLOG
  mv -f $tmpLOG c:/temp/tmpsas.lastrun.sasrun.log
fi

rm $tmpCODE

echo 'View previous run: vi -R c:/temp/tmpsas.lastrun.sasrun.lst c:/temp/tmpsas.lastrun.sasrun.log'

