-- sqlplus -S tars/pw@sed <check_db.sql
PROMPT Checking for invalids...
select object_name from user_objects o where object_type != 'JAVA CLASS' and status = 'INVALID' ORDER BY 1;

PROMPT Checking for locks l10e523...
select s.sid ,s.serial# ,s.username ,s.machine ,s.status ,s.lockwait ,t.used_ublk ,t.used_urec ,t.start_time from v$transaction t inner join v$session s on t.addr = s.taddr where upper(machine) like '%L10E523';
