-- Created: 08-Mar-2022 (Bob Heckel)

create table employees_bak as select * from employees;
alter table employees_bak add constraint employees_bak_PK PRIMARY KEY (employee_id);

CREATE TABLE econtacts (
  econtact_id  NUMBER generated BY DEFAULT AS identity PRIMARY KEY,
  employee_id  NUMBER NOT NULL,
  first_name   VARCHAR2(20) NOT NULL,
  last_name    VARCHAR2(20) NOT NULL,
  phone        VARCHAR2(12) NOT NULL,
  FOREIGN KEY(employee_id) REFERENCES employees_bak(employee_id) ON DELETE CASCADE
);

insert into econtacts values (67, 1003, 'a','b',999);
insert into econtacts values (67, 1009, 'a','b',999);--ORA-00001: unique constraint (ADMIN.SYS_C0042400) violated
insert into econtacts values (67, 1004, 'a','b',999);

delete from econtacts WHERE employee_id=1003;
select * from econtacts;
select * from employees;--1003 now gone from here too

