#!/usr/bin/perl -w
##############################################################################
#     Name: ck4blink.pl
#
#  Summary: Determine if blink is running.
#
#           Win32 (Cygwin) only.
#
#  Created: Sun 18 Aug 2002 09:35:58 (Bob Heckel)
##############################################################################
use strict;

my $the_pgm = 'blink';
my $this_tty = `tty`;
my @psoutput = ();

chomp $this_tty;
my $ttynum = chop $this_tty;  # TODO only sees tty 0-9

# Same as:
# $ ps | awk '{print $3}'
foreach ( `ps` ) {
  chomp;
  my ($junk0, $junk1, $junk2, $junk3, $junk4, $ttyline, $junk5, $junk6, $psline) = 
                                                             split /\s+/, $_;
  ###print "$junk0, $junk1, $junk2, $junk3, $junk4, $ttyline, $junk5,$junk6,  $psline\n";
  push @psoutput, [ $ttyline, $psline ];
}

foreach my $line ( @psoutput ) {
  ###print "@$line[0] and @$line[1]\n";
  if ( @$line[0] =~ /^$ttynum$/o  &&  @$line[1] =~ /$the_pgm/o ) {
    # Blinking already.
    exit 0;
  }
}

# Need to blink.
exit 1;
