#!/usr/local/bin/perl
##############################################################################
#     Name: fujibom
#
#  Summary: Parse Cadence/Agile file into machine usable text.
#           Adapted from IWS fujifile.pl
#
#  Created: Mon, 21 Aug 2000 10:42:47 (Bob Heckel)
##############################################################################

Usage($0, '') if ( $ARGV[0] =~ /-+h.*/ );
  
my $filename = $ARGV[0] || Usage($0, 'No textfile provided');

# E.g. 8_2_ntlx72ba.bom
open(FH, $filename) || Usage($0, $!);

my $cpccode = '';     # Don't use undef.
my $desig   = '';     # Don't use undef.
my %cpchash = ();

while ( <FH> ) {
  # Remove top of page garbage.
  next unless ( $. > 5 );
  next if /^Item|^====/;
  # Elim blank lines (just in case they appear in the future).
  next if /^\s*$/;
  
  # Start new record...
  if ( $_ =~ /^ *(\d+)   / ) { 
    # First flush out any old data if you're on a new record.
    # Finished with CPC record if arrive at a new Item number.
    # The only indication of a new record is a new Item number.
    # Create %cpchash whose keys are cpccodes and values are (references to)
    # arrays of desigs.
    push( @{$cpchash{$cpccode}}, "$desig\t" ) if $1;
    # ... add more push statements here to add other fields besides $desig.
    $cpccode = substr($_, 54, 8);
    $desig = undef;     # Start a new desig which might span several lines.
  }
  # Add to existing record...
  # Use $cleanup_desig to clean data before concat with $desig.
  if ( $cleanup_desig = substr($_, 25, 20) ) {
    $cleanup_desig =~ s/\s+//;       # Clean spaces created from short lines, etc.
    $desig .= $cleanup_desig;
  }
}
close(FH) || Usage($0, "Can't close $file");

DisplayCadence(\%cpchash);


sub DisplayCadence {
  my $rcpchash = $_[0];
  my %cpchash = %$rcpchash;

  foreach $hashkey (sort keys %cpchash) {
    print  "$hashkey\t";     # Set up the cpc's line.
    my @desigline = @{$cpchash{$hashkey}};
    foreach $element ( @desigline ) {
      $element =~ s/^\s+//;      # Ltrim just in case.
      # Warning: input data can have duplicate cpccodes.  I'm assuming that
      # they will always be adjacent to each other.
      # This regex will force the multiple collections of desigs into one.
      $element =~ s/ +\t/,/;
    }
    # There's only one element in @desigline.
    # Elim trailing comma.  Can't do it above due to interference from the
    # duplicate cpc potential and the fact that those elements run together.
    chop($desigline[0]);     
    print $desigline[0], "\n";
  }
}

sub Usage {
  my $errfile  = $_[0];
  my $errmsg   = $_[1];

  if ( $errmsg ) {
    print "$errmsg.  Exiting.\n";
  } else {
    print<<'EOT'

This application parses a Fuji BOM textfile passed to it into a
machine-specific formatted textfile, printing to standard output.

  --------------------------------------------------------------------------- 
 | Sample input file:                                                        |
 |                                                                           |
 |                                                                           |
 |   Title:    Bill of Materials                                             |
 |   Design:   NTLX72BA                                                      |
 |   Date:     Aug 2 9:14:12 2000                                            |
 |   Template: /ntcad/tools/cadence/share/etc/text/concept_msl.bom           |
 |                                                                           |
 |                                                                           |
 |   Item   Part Name         Ref Des                Qty   CPCode        ... |
 |   ====  ===============   ====================    ===   ============  ... |
 |     1   50154L483         R39-R44,R117,           24   A0263806       ... |
 |                           R128-R137,R155,                             ... |
 |                           R295-R297,R314-R316                         ... |
 |     2   50160Z483         E1-E4                    4   A0376368       ... |
 | ...                                                                       |
 |                                                                           |
 |                                                                           |
 | Sample output to screen:                                                  |
 |                                                                           |
 | A0263806     R39-R44,R128-R137,R155,R295-R297,R314-R316                   |
 | A0376368     E1-E4                                                        |
 | ...                                                                       |
  ---------------------------------------------------------------------------
EOT
  }
    print "Usage: $errfile [-h --help] TEXTFILE_TO_PROCESS\n";
    exit -1 ;
}
