#!/usr/bin/perl -w
##############################################################################
#     Name: printfriendly.pl
#
#  Summary: Convert Economist.com page to only PrinterFriendly links.
#
#           For CYGWIN_NT-5.0 PARSIFAL 1.3.10(0.51/3/2) 2002-02-25 11:14 i686
#           and perl 5.6.1
#           installing libwww-perl-5.76.tar.gz and URI-1.28.tar.gz are
#           prerequisites (2006-06-04 horribly messy failure-ridden install
#           seemed to work)
#
#           2006-06-04 not working (and economist changed url format so doubly
#           fscked)
#
#  Created: Sun 21 Dec 2003 21:43:03 (Bob Heckel)
# Modified: Sun 27 Jun 2004 19:25:09 (Bob Heckel)
##############################################################################
use strict;

use Config;
die unless $Config{osname} eq 'cygwin';

my $page = 'http://www.economist.com/printedition/';

use LWP::UserAgent;
if ( $#ARGV > -1 ) {
  die "usage:  printfriendly\nCreates junk.html in /tmp\n";
}

###print "translate $page? ";
###die unless <STDIN> =~ /^y|^yes|^ok/i;


my $ua = new LWP::UserAgent;
# The Economist folks don't take kindly to automated accesses.
$ua->agent("Mozilla/1.6 " . $ua->agent);

my $req = new HTTP::Request GET => $page;
$req->content_type('text/html');
print "DEBUGa: $req\n";

# Pass request to the user agent and get a response back:
my $res = $ua->request($req);
print "DEBUGb: $res\n";

my $tmp = "$0 failed";  # initialize
if ( $res->is_success ) {
  ($tmp = $res->content) =~ s/displayStory/PrinterFriendly/g;
} else {
  print "Error: $page not available\n";
}

open FH, "> /tmp/junk.html" or die "Error: $0: $!";
print FH "<base href='http://www.economist.com'>\n";
print FH $tmp;
close FH;

system 'file:///C:/cygwin/tmp/junk.html';
