'VB_Name
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Program Name: insertheader.bas
'
'      Summary: Insert header row in spreadsheet based on string passed to
'               this function.
'
'      Created: Wed, 08 Sep 1999 10:35:21 (Bob Heckel)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Function InsertHeader()
  On Error GoTo ENTROPY
  Dim sMsg As String
  Dim vTitlearr As Variant
  Dim vArrElement As Variant

  vTitlearr = Array("MTD", "B/(W) JPC", "B/(W) Budget", "YTD", "B/(W) JPC", "B/(W) Budget")
  
  Range("B4").Select
  For Each vArrElement In vTitlearr
    ActiveCell.Value = vArrElement
    ActiveCell.Offset(0, 1).Select
  Next
  
  Range("A1:G4").Select
  With Selection
    .Font.FontStyle = "Bold"
    .HorizontalAlignment = xlCenter
    .VerticalAlignment = xlBottom
    .WrapText = False
    .Orientation = xlHorizontal
  End With
  Cells.EntireColumn.AutoFit
  Range("A1").Select
  InsertHeader = True
Exit Function
   
DAMAGEDEXIT:
  Exit Function

ENTROPY:
  If Err.Number <> 0 Then
    sMsg = "Error # " & Str(Err.Number) & " was generated by " _
              & Err.Source & Chr(13) & "Description: " & Err.Description
  MsgBox sMsg, , "An error has occurred in <Function> " & _
         "<Name unspecified>. " & Erl, Err.HelpFile, Err.HelpContext
  End If
  Resume DAMAGEDEXIT
End Function


