#!/usr/bin/perl -w
##############################################################################
# Program Name: tvan
#
#      Summary: Return n, based on pmt, r, FV
#               Usage: tvan
#
#      Created: Mon, 09 Aug 1999 20:32:52 (Bob Heckel)
##############################################################################

print "Program returns n, given PV, r, FV\n";

print "Enter payment\n";
$pmt = <STDIN>;
print "Enter rate e.g 10%:\n";
$rate = <STDIN>;
$frac = ($rate / 100);
print "Enter FV:\n";
$fv = <STDIN>;

$x = ((($fv / $pmt) * $frac) + 1);
$log_a = log($x);

$y = $frac + 1;
$log_b = log($y);

$retme = ($log_a / $log_b);

print "$retme is the number of periods.\n";

