#!/usr/bin/perl -w
##############################################################################
#     Name: uvi
#
#  Summary: Edit a file without changing its access times.
#
#           TODO allow wildcarding fnames
#
#  Adapted: Tom Christiansen
# Modified: Mon 26 Nov 2001 11:03:24 (Bob Heckel)
##############################################################################

$file = shift or die "usage: uvi filename\n";

($atime, $mtime) = (stat($file))[8,9];

system($ENV{EDITOR} || "vi", $file);

utime($atime, $mtime, $file)
                          or die "Couldn't restore $file to orig times: $!\n";
